class XpathsExerciseFive:
    first_name = '//input[@id="customer.firstName"]'
    last_name = '//input[@id="customer.lastName"]'
    address = '//input[@id="customer.address.street"]'
    city = '//input[@id="customer.address.city"]'
    state = '//input[@id="customer.address.state"]'
    zipcode = '//input[@id="customer.address.zipCode"]'
    phone = '//input[@id="customer.phoneNumber"]'
    ssn = '//input[@id="customer.ssn"]'
    username = '//input[@id="customer.username"]'
    password = '//input[@id="customer.password"]'
    confirm_password = '//input[@id="repeatedPassword"]'
    submit_button = '//form[@id="customerForm"]//input[@type="submit"]'
    success = '//p[contains(text(), "Your account was created successfully. You are now logged in.")]'
    url = 'https://parabank.parasoft.com/parabank/register.htm'
